### ISSUE TITLE
Пофиксить футер на странице "Каталог"

### ISSUE THREAD

**Issue by egor-teapot** [Internship-Spectre/remesliniki_project#10]

**Comment by TheHexReader** [comment]
Что конкретно нужно исправить?

**Comment by egor-teapot** [comment]
@TheHexReader 
Домашняя
![Screenshot from 2023-04-18 19-37-41](https://user-images.githubusercontent.com/82697354/232845663-4fbd3bec-3c5f-45b4-971f-61ee35f8f45b.png)

Каталог
![Screenshot from 2023-04-18 19-37-25](https://user-images.githubusercontent.com/82697354/232845750-67e7472a-cf33-4808-8f2f-f4120dd6f34e.png)

**Comment by TheHexReader** [comment]
@egor-teapot
До сих пор не понятно, что с футером не так. Какая из этих картинок показывает неправильный футер? Какой футер должен быть?

**Comment by TheHexReader** [comment]
Сделал
