### ISSUE TITLE
Отсуствует возможность разлогинится

### ISSUE THREAD

**Issue by egor-teapot** [Internship-Spectre/remesliniki_project#3]
В навбар необходимо добавить возможность выйти из аккаунта

**Comment by TheHexReader** [comment]
Взял в работу

**Comment by TheHexReader** [comment]
Сделал, вот [комит](https://github.com/Internship-Spectre/remesliniki_project/commit/54ab87187de9094e8f59a808a6a51dfc2e6de50d).
